version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15-alpine
    container_name: studyapp-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - studyapp-network

  # 백엔드 API 서버
  backend:
    build: .
    container_name: studyapp-backend
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - studyapp-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  studyapp-network:
    driver: bridge